- name: Running first playbook
  hosts: all
  gather_facts: False
  become: yes
  tasks:
    
    # - name: install the latest version of Apache
    #   yum:
    #     name: httpd
    #     state: present

    # - name: ensure a list of packages installed
    #   yum:
    #     name: "{{ packages }}"
    #   vars:
    #     packages:
    #     - httpd
    #     - httpd-tools

    - name: remove the Apache package
      command: bash -lc "ip a"
      register: versioas

    - debug:
        msg: " {{ versioas }}"